# Generated by Django 5.2.3 on 2025-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotanicalRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binomial', models.CharField(max_length=250)),
                ('common_name', models.CharField(max_length=250)),
                ('botanical_family', models.CharField(max_length=250)),
                ('genus', models.CharField(max_length=250)),
                ('species', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('height', models.FloatField()),
                ('diameter', models.FloatField()),
                ('stem_type', models.CharField(choices=[('Ereto', 'Caule Ereto'), ('Trepador', 'Caule Trepador'), ('Rastejante', 'Caule Rastejante'), ('Escandente', 'Caule Escandente'), ('Tubérculo', 'Caule Tubérculo'), ('Rizoma', 'Caule Rizoma'), ('Bulbo', 'Caule Bulbo'), ('Estolho', 'Caule Estolho'), ('Sarmentoso', 'Caule Sarmentoso'), ('Lenhoso', 'Caule Lenhoso'), ('Herbáceo', 'Caule Herbáceo'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('leaf_type', models.CharField(choices=[('Simples', 'Folha Simples'), ('Composta', 'Folha Composta'), ('Palmaticomposta', 'Folha Palmaticomposta'), ('Pinnaticomposta', 'Folha Pinnaticomposta'), ('Bipinnaticomposta', 'Folha Bipinnaticomposta'), ('Trifoliolada', 'Folha Trifoliolada'), ('Digitada', 'Folha Digitada'), ('Aciculada', 'Folha Aciculada'), ('Escamosa', 'Folha Escamosa'), ('Sésil', 'Folha Sésil'), ('Peciolada', 'Folha Peciolada'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('flower_type', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('H', 'Hermafrodita'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('flowering_period', models.CharField(choices=[('Primavera', 'Primavera'), ('Verão', 'Verão'), ('Outono', 'Outono'), ('Inverno', 'Inverno'), ('O ano todo', 'O ano todo'), ('Estação chuvosa', 'Estação chuvosa'), ('Estação seca', 'Estação seca'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('fruit_type', models.CharField(choices=[('Baga', 'Baga'), ('Drupa', 'Drupa'), ('Legume', 'Legume'), ('Sâmara', 'Sâmara'), ('Cápsula', 'Cápsula'), ('Núcua', 'Núcua'), ('Aquênio', 'Aquênio'), ('Noz', 'Noz'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('fruiting_period', models.CharField(choices=[('Primavera', 'Primavera'), ('Verão', 'Verão'), ('Outono', 'Outono'), ('Inverno', 'Inverno'), ('O ano todo', 'O ano todo'), ('Estação chuvosa', 'Estação chuvosa'), ('Estação seca', 'Estação seca'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('morphological_observations', models.TextField(blank=True, null=True)),
                ('soil_type', models.CharField(choices=[('Arenoso', 'Solo Arenoso'), ('Argiloso', 'Solo Argiloso'), ('Siltoso', 'Solo Siltoso'), ('Massapê', 'Solo Massapê'), ('Turfoso', 'Solo Turfoso'), ('Calcário', 'Solo Calcário'), ('Salino', 'Solo Salino'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('soil_pH', models.FloatField()),
                ('moisture', models.CharField(choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('lighting', models.CharField(choices=[('Sol pleno', 'Sol pleno'), ('Meia sombra', 'Meia sombra'), ('Sombra', 'Sombra'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('temperature', models.FloatField()),
                ('climate', models.CharField(choices=[('Tropical', 'Tropical'), ('Subtropical', 'Subtropical'), ('Temperado', 'Temperado'), ('Árido', 'Árido'), ('Mediterrâneo', 'Mediterrâneo'), ('Polar', 'Polar'), ('U', 'Desconhecido')], default='U', max_length=100)),
                ('water_requirement', models.CharField(choices=[('B', 'Baixa'), ('M', 'Moderada'), ('A', 'Alta'), ('U', 'Desconhecido')], default='U', max_length=1)),
                ('watering_frequency', models.CharField(choices=[('D', 'Diária'), ('2', 'Duas vezes por semana'), ('S', 'Semanal'), ('Q', 'Quinzenal'), ('M', 'Mensal'), ('U', 'Desconhecido')], default='U', max_length=1)),
                ('fertilization_type', models.CharField(choices=[('O', 'Orgânica'), ('Q', 'Química'), ('F', 'Foliar'), ('N', 'Nenhuma')], default='N', max_length=1)),
                ('need_for_pruning', models.BooleanField(default=False)),
                ('susceptibility', models.TextField(blank=True, null=True)),
                ('cultivation_notes', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('specific_location', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude_meters', models.FloatField(blank=True, null=True)),
                ('biome', models.CharField(blank=True, max_length=100, null=True)),
                ('ecosystem', models.CharField(blank=True, max_length=150, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_by', models.CharField(max_length=150)),
            ],
        ),
    ]
