# Generated by Django 5.2.3 on 2025-06-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botanicalregister',
            name='flower_image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/flower/'),
        ),
        migrations.AddField(
            model_name='botanicalregister',
            name='fruit_image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/fruit/'),
        ),
        migrations.AddField(
            model_name='botanicalregister',
            name='general_image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/general/'),
        ),
        migrations.AddField(
            model_name='botanicalregister',
            name='leaf_image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/leaf/'),
        ),
        migrations.AddField(
            model_name='botanicalregister',
            name='stem_image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/stem/'),
        ),
    ]
