# Generated by Django 5.2.3 on 2025-06-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botanicalregister',
            name='Fruiting_period',
        ),
        migrations.AlterField(
            model_name='botanicalregister',
            name='climate',
            field=models.CharField(choices=[('Tropical', 'Tropical'), ('Subtropical', 'Subtropical'), ('Temperado', 'Temperado'), ('Árido', 'Árido'), ('Mediterrâneo', 'Mediterrâneo'), ('Polar', 'Polar'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='botanicalregister',
            name='flower_type',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('H', 'Hermafrodita'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='botanicalregister',
            name='flowering_period',
            field=models.CharField(choices=[('Primavera', 'Primavera'), ('Verão', 'Verão'), ('Outono', 'Outono'), ('Inverno', 'Inverno'), ('O ano todo', 'O ano todo'), ('Estação chuvosa', 'Estação chuvosa'), ('Estação seca', 'Estação seca'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='botanicalregister',
            name='fruit_type',
            field=models.CharField(choices=[('Baga', 'Baga'), ('Drupa', 'Drupa'), ('Legume', 'Legume'), ('Sâmara', 'Sâmara'), ('Cápsula', 'Cápsula'), ('Núcua', 'Núcua'), ('Aquênio', 'Aquênio'), ('Noz', 'Noz'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='botanicalregister',
            name='leaf_type',
            field=models.CharField(choices=[('Simples', 'Folha Simples'), ('Composta', 'Folha Composta'), ('Palmaticomposta', 'Folha Palmaticomposta'), ('Pinnaticomposta', 'Folha Pinnaticomposta'), ('Bipinnaticomposta', 'Folha Bipinnaticomposta'), ('Trifoliolada', 'Folha Trifoliolada'), ('Digitada', 'Folha Digitada'), ('Aciculada', 'Folha Aciculada'), ('Escamosa', 'Folha Escamosa'), ('Sésil', 'Folha Sésil'), ('Peciolada', 'Folha Peciolada'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='botanicalregister',
            name='lighting',
            field=models.CharField(choices=[('Sol pleno', 'Sol pleno'), ('Meia sombra', 'Meia sombra'), ('Sombra', 'Sombra'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='botanicalregister',
            name='moisture',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='botanicalregister',
            name='soil_type',
            field=models.CharField(choices=[('Arenoso', 'Solo Arenoso'), ('Argiloso', 'Solo Argiloso'), ('Siltoso', 'Solo Siltoso'), ('Massapê', 'Solo Massapê'), ('Turfoso', 'Solo Turfoso'), ('Calcário', 'Solo Calcário'), ('Salino', 'Solo Salino'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='botanicalregister',
            name='stem_type',
            field=models.CharField(choices=[('Ereto', 'Caule Ereto'), ('Trepador', 'Caule Trepador'), ('Rastejante', 'Caule Rastejante'), ('Escandente', 'Caule Escandente'), ('Tubérculo', 'Caule Tubérculo'), ('Rizoma', 'Caule Rizoma'), ('Bulbo', 'Caule Bulbo'), ('Estolho', 'Caule Estolho'), ('Sarmentoso', 'Caule Sarmentoso'), ('Lenhoso', 'Caule Lenhoso'), ('Herbáceo', 'Caule Herbáceo'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
        migrations.AddField(
            model_name='botanicalregister',
            name='fruiting_period',
            field=models.CharField(choices=[('Primavera', 'Primavera'), ('Verão', 'Verão'), ('Outono', 'Outono'), ('Inverno', 'Inverno'), ('O ano todo', 'O ano todo'), ('Estação chuvosa', 'Estação chuvosa'), ('Estação seca', 'Estação seca'), ('U', 'Desconhecido')], default='U', max_length=100),
        ),
    ]
